DROP DATABASE IF EXISTS market;
CREATE DATABASE market;
USE market;
 CREATE TABLE Categories(
   C_ID INT NOT NULL AUTO_INCREMENT,
   C_Name VARCHAR(50) NOT NULL UNIQUE,
   PRIMARY KEY(C_ID)
 );
 CREATE TABLE SubCategories(
   Sub_ID INT NOT NULL AUTO_INCREMENT,
   Sub_Name VARCHAR(50) NOT NULL ,
   C_ID INT ,
   PRIMARY KEY(Sub_ID),
   CONSTRAINT Parent_C FOREIGN KEY(C_ID) REFERENCES Categories(C_ID)
   
 );